// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umwkinjveokfmjxmjvnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtd2tpbmp2ZW9rZm1qeG1qdm56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMDA2NzIsImV4cCI6MjA1ODc3NjY3Mn0.pUkaCU_FsRb0kHl3uxu1zRyeagYz6cj5Jxp1ZO2bRXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);